from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.utils import timezone


class Role(models.TextChoices):
    ADMIN = "admin", "Администратор"
    TRAINER = "trainer", "Тренер"
    PARENT = "parent", "Родитель"


class User(AbstractUser):
    """Auth identity. Domain attributes live in ParentAccount / Trainer profiles."""
    role = models.CharField(max_length=16, choices=Role.choices, default=Role.PARENT)

    def __str__(self):
        return f"{self.get_full_name() or self.username} ({self.get_role_display()})"


class ParentAccount(models.Model):
    """Rule 7: the login owner, notification recipient, RODO consent subject.
    One parent -> many students. The phone is a family-level contact: one phone
    per family, no duplicates (DECISIONS.md #3); children carry no own phone."""
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="parent_account")
    phone = models.CharField(
        max_length=32, blank=True,
        help_text="Один телефон на семью (без дубликатов)")
    email = models.EmailField(blank=True)
    telegram_chat_id = models.CharField(max_length=64, blank=True)
    instagram_username = models.CharField(max_length=30, blank=True)
    preferred_language = models.CharField(max_length=12, default=settings.SWIMCRM_DEFAULT_LANGUAGE)
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        constraints = [
            # DECISIONS.md #3: one phone per family, unique across families
            # (partial: legacy/blank phones are not forced unique).
            models.UniqueConstraint(
                fields=["phone"], condition=~Q(phone=""), name="uniq_parent_phone_nonblank"),
        ]

    def __str__(self):
        return self.user.get_full_name() or self.user.username


class AccessPurpose(models.TextChoices):
    ACTIVATION = "activation", "Activation"
    RECOVERY = "recovery", "Recovery"


class AccountActivation(models.Model):
    """Single-use, hash-only credential for client or trainer portal access."""
    parent = models.ForeignKey(
        ParentAccount, null=True, blank=True, on_delete=models.CASCADE,
        related_name="activations")
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE,
        related_name="account_activations")
    purpose = models.CharField(
        max_length=16, choices=AccessPurpose.choices, default=AccessPurpose.ACTIVATION)
    token_hash = models.CharField(max_length=64, unique=True)
    expires_at = models.DateTimeField()
    used_at = models.DateTimeField(null=True, blank=True)
    created_by = models.ForeignKey(
        User, null=True, blank=True, on_delete=models.SET_NULL,
        related_name="created_client_activations")
    created_at = models.DateTimeField(default=timezone.now)

    @property
    def is_valid(self):
        return bool(self.user_id or self.parent_id) and self.used_at is None and self.expires_at > timezone.now()


class Trainer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="trainer_profile")
    phone = models.CharField(max_length=32, blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.user.get_full_name() or self.user.username


class ConsentType(models.TextChoices):
    DATA_PROCESSING = "data", "Обработка персональных данных"
    EMAIL = "email", "Рассылки по email"
    SMS = "sms", "SMS"
    TELEGRAM = "telegram", "Telegram"


class Consent(models.Model):
    """RODO: granular consent per channel + data processing, revocable (rule 5.6)."""
    parent = models.ForeignKey(ParentAccount, on_delete=models.CASCADE, related_name="consents")
    type = models.CharField(max_length=16, choices=ConsentType.choices)
    granted = models.BooleanField(default=False)
    granted_at = models.DateTimeField(null=True, blank=True)
    revoked_at = models.DateTimeField(null=True, blank=True)
    policy_version = models.CharField(max_length=32, blank=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["parent", "type"], name="uniq_parent_consent_type"),
        ]

    def grant(self, policy_version=""):
        self.granted = True
        self.granted_at = timezone.now()
        self.revoked_at = None
        self.policy_version = policy_version
        self.save()

    def revoke(self):
        self.granted = False
        self.revoked_at = timezone.now()
        self.save()

    @property
    def is_active(self):
        return self.granted and self.revoked_at is None

    def __str__(self):
        return f"{self.parent} · {self.get_type_display()} · {'да' if self.is_active else 'нет'}"


class AdminOTPDevice(models.Model):
    """TOTP device for admin/staff 2FA. Secret is generated by setup command."""
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="admin_otp_device")
    secret = models.CharField(max_length=64)
    is_confirmed = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now)
    confirmed_at = models.DateTimeField(null=True, blank=True)
    last_used_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"2FA · {self.user}"
