# Generated by Django 5.1.15 on 2026-07-01 08:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('payment_reminder', 'Напоминание об оплате'), ('session_reminder', 'Напоминание о тренировке'), ('subscription_end', 'Окончание абонемента'), ('renewal_needed', 'Необходимость продления'), ('schedule_change', 'Изменение расписания')], max_length=32)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('sms', 'SMS'), ('push', 'Push')], max_length=16)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('sent', 'Отправлено'), ('delivered', 'Доставлено'), ('failed', 'Ошибка')], default='queued', max_length=16)),
                ('retries', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.parentaccount')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('payment_reminder', 'Напоминание об оплате'), ('session_reminder', 'Напоминание о тренировке'), ('subscription_end', 'Окончание абонемента'), ('renewal_needed', 'Необходимость продления'), ('schedule_change', 'Изменение расписания')], max_length=32)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('sms', 'SMS'), ('push', 'Push')], max_length=16)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(help_text='Переменные: {student}, {amount}, {date} и т.п.')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event_type', 'channel'), name='uniq_template_event_channel')],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('payment_reminder', 'Напоминание об оплате'), ('session_reminder', 'Напоминание о тренировке'), ('subscription_end', 'Окончание абонемента'), ('renewal_needed', 'Необходимость продления'), ('schedule_change', 'Изменение расписания')], max_length=32)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('sms', 'SMS'), ('push', 'Push')], max_length=16)),
                ('offset_minutes', models.IntegerField(default=0, help_text='Смещение к моменту события в минутах (может быть отрицательным)')),
                ('is_active', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notifications.notificationtemplate')),
            ],
        ),
    ]
