# Generated by Django 5.1.15 on 2026-07-05

from django.db import migrations, models


EVENT_TYPE_CHOICES = [
    ("payment_reminder", "Напоминание об оплате"),
    ("session_reminder", "Напоминание о тренировке"),
    ("subscription_end", "Окончание абонемента"),
    ("renewal_needed", "Необходимость продления"),
    ("schedule_change", "Изменение расписания"),
    ("mass_mailing", "Массовая рассылка"),
]


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notificationlog_dedup_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="event_type",
            field=models.CharField(choices=EVENT_TYPE_CHOICES, max_length=32),
        ),
        migrations.AlterField(
            model_name="notificationrule",
            name="event_type",
            field=models.CharField(choices=EVENT_TYPE_CHOICES, max_length=32),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="event_type",
            field=models.CharField(choices=EVENT_TYPE_CHOICES, max_length=32),
        ),
    ]
