# Generated by Django 5.1.15 on 2026-07-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_delivery_details_and_rule_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('payment_reminder', 'Payment reminder'), ('session_reminder', 'Session reminder'), ('subscription_end', 'Subscription end'), ('renewal_needed', 'Renewal needed'), ('schedule_change', 'Schedule change'), ('mass_mailing', 'Mass mailing')], max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='queued', max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='event_type',
            field=models.CharField(choices=[('payment_reminder', 'Payment reminder'), ('session_reminder', 'Session reminder'), ('subscription_end', 'Subscription end'), ('renewal_needed', 'Renewal needed'), ('schedule_change', 'Schedule change'), ('mass_mailing', 'Mass mailing')], max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='offset_minutes',
            field=models.IntegerField(default=0, help_text='Offset from event time in minutes. Negative means before the event.'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='body',
            field=models.TextField(help_text='Variables: {student}, {amount}, {date}, etc.'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('payment_reminder', 'Payment reminder'), ('session_reminder', 'Session reminder'), ('subscription_end', 'Subscription end'), ('renewal_needed', 'Renewal needed'), ('schedule_change', 'Schedule change'), ('mass_mailing', 'Mass mailing')], max_length=32),
        ),
    ]
