# Generated by Django 5.1.15 on 2026-07-14 18:33

from django.db import migrations, models


def disable_unsupported_push(apps, schema_editor):
    NotificationRule = apps.get_model("notifications", "NotificationRule")
    NotificationLog = apps.get_model("notifications", "NotificationLog")

    NotificationRule.objects.filter(channel="push").update(is_active=False)
    NotificationLog.objects.filter(channel="push", status="queued").update(
        status="failed",
        error="Push notifications are not supported in this release.",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notificationlog_event_type_and_more'),
    ]

    operations = [
        migrations.RunPython(disable_unsupported_push, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('sms', 'SMS')], max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('sms', 'SMS')], max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('sms', 'SMS')], max_length=16),
        ),
    ]
