# Generated by Django 5.1.15 on 2026-07-15 01:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notificationlog_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='scheduled_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('deferred', 'Deferred'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='queued', max_length=16),
        ),
        migrations.CreateModel(
            name='QuietHoursPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('sms', 'SMS')], max_length=16)),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('timezone', models.CharField(default='Europe/Warsaw', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('channel', 'starts_at', 'ends_at', 'timezone'), name='uniq_quiet_hours_channel_window_timezone')],
            },
        ),
    ]
