# Generated by Django 5.1.15 on 2026-07-15 02:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notificationlog_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='language_code',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.CreateModel(
            name='NotificationTemplateTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=12)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='notifications.notificationtemplate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('template', 'language_code'), name='uniq_notification_template_translation_language')],
            },
        ),
    ]
