# Generated by Django 5.1.15 on 2026-07-02 08:52

import billing.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), billing.validators.validate_receipt_size, billing.validators.validate_receipt_content]),
        ),
    ]
