# Generated by Django 5.2.16 on 2026-07-23 04:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_payment_sources_and_events(apps, schema_editor):
    Payment = apps.get_model("billing", "Payment")
    PaymentEvent = apps.get_model("billing", "PaymentEvent")

    client_payment_ids = Payment.objects.filter(
        created_by__role="parent",
    ).values_list("id", flat=True)
    Payment.objects.filter(id__in=client_payment_ids).update(source="client_top_up")

    events = []
    for payment in Payment.objects.all().iterator():
        if payment.status == "confirmed":
            event_type = "confirmed"
            actor_id = payment.confirmed_by_id
            created_at = payment.confirmed_at or payment.created_at
        elif payment.status == "rejected":
            event_type = "rejected"
            actor_id = payment.confirmed_by_id
            created_at = payment.confirmed_at or payment.created_at
        elif payment.source == "client_top_up":
            event_type = "requested"
            actor_id = payment.created_by_id
            created_at = payment.created_at
        else:
            event_type = "created"
            actor_id = payment.created_by_id
            created_at = payment.created_at
        events.append(PaymentEvent(
            payment_id=payment.id,
            event_type=event_type,
            actor_id=actor_id,
            from_status="",
            to_status=payment.status,
            amount_minor=payment.amount_minor,
            currency=payment.currency,
            created_at=created_at,
        ))
    PaymentEvent.objects.bulk_create(events)


def reverse_backfill(apps, schema_editor):
    apps.get_model("billing", "PaymentEvent").objects.all().delete()
    apps.get_model("billing", "Payment").objects.update(source="admin")


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_rename_transfer_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='source',
            field=models.CharField(choices=[('admin', 'Создан администратором'), ('client_top_up', 'Запрос клиента на пополнение')], default='admin', max_length=24),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_minor',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Платёж создан'), ('requested', 'Запрос на пополнение отправлен'), ('confirmed', 'Платёж подтверждён'), ('rejected', 'Платёж отклонён')], max_length=16)),
                ('from_status', models.CharField(blank=True, choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждён'), ('rejected', 'Отклонён')], max_length=16)),
                ('to_status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждён'), ('rejected', 'Отклонён')], max_length=16)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EUR'), ('USD', 'USD')], max_length=3)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='billing.payment')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.RunPython(backfill_payment_sources_and_events, reverse_backfill),
    ]
