# Generated by Django 5.2.16 on 2026-07-25 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('billing', '0004_payment_source_alter_payment_amount_minor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='attendance',
            field=models.ForeignKey(blank=True, help_text='Заполняется для платного разового занятия', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='attendance.attendancerecord'),
        ),
    ]
