# Generated by Django 5.1.15 on 2026-07-01 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=120)),
                ('max_participants', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='catalog.group')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='accounts.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('group', 'Групповая'), ('individual', 'Индивидуальная')], default='group', max_length=16)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('location', models.CharField(max_length=120)),
                ('max_participants', models.PositiveIntegerField()),
                ('is_manually_modified', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='catalog.group')),
                ('individual_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_sessions', to='students.student')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='scheduling.recurringtemplate')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='accounts.trainer')),
            ],
            options={
                'indexes': [models.Index(fields=['trainer', 'start_at'], name='scheduling__trainer_909457_idx'), models.Index(fields=['group', 'start_at'], name='scheduling__group_i_1fbdfd_idx')],
                'constraints': [models.UniqueConstraint(fields=('trainer', 'start_at'), name='uniq_trainer_start')],
            },
        ),
    ]
