# Generated by Django 5.1.15 on 2026-07-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_parentaccount_phone_and_more'),
        ('catalog', '0001_initial'),
        ('scheduling', '0002_trainer_overlap_exclusion_pg'),
        ('students', '0002_remove_student_phone'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', False), ('individual_student__isnull', True)), models.Q(('group__isnull', True), ('individual_student__isnull', False)), _connector='OR'), name='session_group_xor_individual'),
        ),
    ]
