# Generated by Django 5.1.15 on 2026-07-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_session_session_group_xor_individual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('group', 'Групповая'), ('individual', 'Индивидуальная'), ('split', 'Split')], default='group', max_length=16),
        ),
    ]
