# Generated by Codex for the hybrid rewrite waitlist MVP.

import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0005_location_session_type_config"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitlistEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("priority", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("promoted", "Promoted"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="scheduling.session",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waitlist_entries",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "priority", "created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="waitlistentry",
            index=models.Index(fields=["session", "status", "priority"], name="scheduling__session_ba48c1_idx"),
        ),
        migrations.AddIndex(
            model_name="waitlistentry",
            index=models.Index(fields=["student", "status"], name="scheduling__student_61feca_idx"),
        ),
        migrations.AddConstraint(
            model_name="waitlistentry",
            constraint=models.UniqueConstraint(fields=("session", "student"), name="uniq_waitlist_session_student"),
        ),
    ]
