# Generated by Codex for waitlist promotion into concrete session rosters.

import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0006_waitlist_entry"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionParticipant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("waitlist", "Waitlist")],
                        default="manual",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("cancelled", "Cancelled")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="scheduling.session",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="session_participations",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="sessionparticipant",
            index=models.Index(fields=["session", "status"], name="scheduling__session_5ed0d7_idx"),
        ),
        migrations.AddIndex(
            model_name="sessionparticipant",
            index=models.Index(fields=["student", "status"], name="scheduling__student_da657e_idx"),
        ),
        migrations.AddConstraint(
            model_name="sessionparticipant",
            constraint=models.UniqueConstraint(fields=("session", "student"), name="uniq_session_participant_student"),
        ),
    ]
