# Generated by Codex for trainer substitution payroll support.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_parentaccount_preferred_language"),
        ("scheduling", "0007_session_participant"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="substitute_trainer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="substituted_sessions",
                to="accounts.trainer",
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["substitute_trainer", "start_at"],
                name="scheduling__subst_8d1a1f_idx",
            ),
        ),
    ]
