# Generated by Django 5.2.16 on 2026-10-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_session_requires_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistentry',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('promoted', 'Promoted'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=16),
        ),
    ]
