# Generated by Django 5.2.16 on 2026-10-04 21:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def attach_existing_types(apps, schema_editor):
    Config = apps.get_model('scheduling', 'SessionTypeConfig')
    Session = apps.get_model('scheduling', 'Session')
    for code in ('group', 'individual', 'split'):
        config = Config.objects.filter(code=code).first()
        if config:
            Config.objects.filter(pk=config.pk).update(base_type=code)
            Session.objects.filter(session_type=code, session_type_config__isnull=True).update(
                session_type_config_id=config.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0014_alter_waitlistentry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_type_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='scheduling.sessiontypeconfig'),
        ),
        migrations.AddField(
            model_name='sessiontypeconfig',
            name='base_type',
            field=models.CharField(choices=[('group', 'Групповая'), ('individual', 'Индивидуальная'), ('split', 'Split')], default='group', max_length=16),
        ),
        migrations.AlterField(
            model_name='sessiontypeconfig',
            name='code',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_-]*$', 'Use lowercase Latin letters, digits, - or _; start with a letter.')]),
        ),
        migrations.RunPython(attach_existing_types, migrations.RunPython.noop),
    ]
