# Generated by Django 5.1.15 on 2026-07-15 02:20

import django.db.models.deletion
import localization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True, validators=[localization.models.validate_language_code])),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DictionaryKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['domain', 'code'],
                'constraints': [models.UniqueConstraint(fields=('domain', 'code'), name='uniq_dictionary_domain_code')],
            },
        ),
        migrations.CreateModel(
            name='DictionaryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=12, validators=[localization.models.validate_language_code])),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='localization.dictionarykey')),
            ],
            options={
                'ordering': ['key__domain', 'key__code', 'language_code'],
                'constraints': [models.UniqueConstraint(fields=('key', 'language_code'), name='uniq_dictionary_translation_key_language')],
            },
        ),
    ]
