API_CONTRACT = {
    "version": "2026-07-15",
    "base_path": "/api/",
    "auth": {
        "type": "django-session",
        "login": {
            "csrf": "GET /api/csrf/ first, then POST /api/auth/login/.",
            "body": ["login|username|email", "password"],
            "logout": "POST /api/auth/logout/",
        },
        "notes": [
            "Admin endpoints require role=admin or superuser.",
            "Trainer endpoints require role=trainer or superuser.",
            "Client endpoints expose role=client while the internal role remains parent.",
        ],
    },
    "conventions": {
        "dates": "YYYY-MM-DD",
        "datetimes": "ISO 8601 with timezone; naive values are interpreted in server timezone.",
        "money": "amount_minor is stored in grosze/cents; formatted amount is returned as amount.",
        "errors": "API errors return JSON: {\"error\": ...}.",
    },
    "resources": {
        "account": [
            "id", "username", "full_name", "email", "phone", "telegram_chat_id",
            "preferred_language", "created_at",
        ],
        "participant": [
            "id", "first_name", "last_name", "full_name", "email", "is_active",
            "is_account_holder", "group", "client_phone", "emergency_contact_name",
            "emergency_contact_phone",
        ],
        "trainer": ["id", "username", "full_name", "email", "phone", "is_active", "groups_count"],
        "group": ["id", "name", "description", "default_trainer", "is_active", "participants_count"],
        "subscription_type": [
            "id", "name", "price", "price_minor", "currency", "duration_days",
            "sessions_count", "is_unlimited", "is_individual", "is_active",
        ],
        "subscription": [
            "id", "participant_id", "subscription_type_id", "type", "status",
            "start_date", "base_end_date", "effective_end_date", "grace_end_date",
            "remaining_sessions",
        ],
        "charge": [
            "id", "participant_id", "participant", "subscription_id", "description",
            "amount", "amount_minor", "currency", "due_date", "created_at",
        ],
        "payment": [
            "id", "participant_id", "participant", "amount", "amount_minor", "currency",
            "paid_at", "method", "status", "comment", "confirmed_by", "confirmed_at",
            "created_at",
        ],
        "session": [
            "id", "template_id", "start_at", "end_at", "location", "session_type",
            "trainer_id", "trainer", "substitute_trainer_id", "substitute_trainer",
            "effective_trainer_id", "effective_trainer", "group", "individual_student_id", "is_cancelled",
            "is_manually_modified", "max_participants", "waitlist_active_count", "notes",
        ],
        "waitlist_entry": [
            "id", "session_id", "student_id", "participant_id", "student", "priority",
            "status", "note", "created_at", "updated_at",
        ],
        "location": ["id", "code", "name", "address", "timezone", "is_active", "created_at", "updated_at"],
        "session_type_config": [
            "id", "code", "label", "default_capacity", "is_active", "created_at", "updated_at",
        ],
        "payroll_scheme": ["id", "name", "location", "is_active", "created_at", "updated_at"],
        "payroll_rule": [
            "id", "scheme_id", "session_type", "rule_type", "base_amount_minor",
            "currency", "min_clients_threshold", "extra_client_amount_minor", "is_active",
        ],
        "payroll_period": [
            "id", "date_from", "date_to", "location", "status",
            "totals_by_trainer", "calculations?",
        ],
        "language": ["id", "code", "name", "is_active"],
        "dictionary_key": ["id", "domain", "code", "is_active"],
        "dictionary_translation": ["id", "key_id", "domain", "code", "language_code", "value"],
        "notification_template_translation": [
            "id", "template_id", "event_type", "channel", "language_code", "subject", "body",
        ],
    },
    "endpoints": [
        {
            "method": "POST",
            "path": "/api/auth/login/",
            "roles": ["anonymous"],
            "description": "Production session login. Accepts username or email in login/username/email.",
            "body": ["login", "password"],
        },
        {
            "method": "POST",
            "path": "/api/auth/logout/",
            "roles": ["admin", "trainer", "client"],
            "description": "Destroy current Django session.",
        },
        {
            "method": "GET",
            "path": "/api/me/",
            "roles": ["admin", "trainer", "client"],
            "description": "Current authenticated user profile.",
        },
        {
            "method": "GET",
            "path": "/api/admin/readiness/",
            "roles": ["admin"],
            "description": "Production readiness report: database, migrations, runtime/media paths, NocoBase integration tokens.",
        },
        {
            "method": "GET",
            "path": "/api/admin/ops-status/",
            "roles": ["admin"],
            "description": "Operational status snapshot: notification queue, receipt cleanup backlog, Celery beat schedule.",
        },
        {
            "method": "GET",
            "path": "/api/client/overview/",
            "roles": ["client"],
            "description": "Client account and participant overview.",
            "response_keys": ["account", "participants", "students"],
        },
        {"method": "GET", "path": "/api/nocobase/health/", "roles": ["nocobase"], "auth": "NOCOBASE_BRIDGE_TOKEN"},
        {"method": "GET", "path": "/api/nocobase/ops-status/", "roles": ["nocobase"], "auth": "NOCOBASE_BRIDGE_TOKEN"},
        {"method": "GET", "path": "/api/nocobase/clients/", "roles": ["nocobase"], "auth": "NOCOBASE_BRIDGE_TOKEN", "query": ["q", "active", "limit"]},
        {"method": "GET", "path": "/api/nocobase/debtors/", "roles": ["nocobase"], "auth": "NOCOBASE_BRIDGE_TOKEN"},
        {"method": "GET", "path": "/api/nocobase/payroll/periods/", "roles": ["nocobase"], "auth": "NOCOBASE_BRIDGE_TOKEN", "query": ["location", "status"]},
        {"method": "GET", "path": "/api/nocobase/payroll/periods/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_BRIDGE_TOKEN"},
        {"method": "GET", "path": "/api/nocobase/config/quiet-hours/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "POST", "path": "/api/nocobase/config/quiet-hours/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN", "body": ["channel", "starts_at", "ends_at", "timezone", "is_active?"]},
        {"method": "GET", "path": "/api/nocobase/config/quiet-hours/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "POST/PATCH/PUT", "path": "/api/nocobase/config/quiet-hours/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "DELETE", "path": "/api/nocobase/config/quiet-hours/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "GET", "path": "/api/nocobase/config/notification-templates/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "POST", "path": "/api/nocobase/config/notification-templates/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN", "body": ["event_type", "channel", "subject?", "body"]},
        {"method": "GET", "path": "/api/nocobase/config/notification-templates/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "POST/PATCH/PUT", "path": "/api/nocobase/config/notification-templates/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "DELETE", "path": "/api/nocobase/config/notification-templates/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "GET", "path": "/api/nocobase/config/notification-rules/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "POST", "path": "/api/nocobase/config/notification-rules/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN", "body": ["event_type", "channel", "template_id", "offset_minutes", "is_active?"]},
        {"method": "GET", "path": "/api/nocobase/config/notification-rules/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "POST/PATCH/PUT", "path": "/api/nocobase/config/notification-rules/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "DELETE", "path": "/api/nocobase/config/notification-rules/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "GET", "path": "/api/nocobase/config/locations/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "POST", "path": "/api/nocobase/config/locations/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN", "body": ["code", "name", "address?", "timezone?", "is_active?"]},
        {"method": "GET", "path": "/api/nocobase/config/locations/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "POST/PATCH/PUT", "path": "/api/nocobase/config/locations/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "DELETE", "path": "/api/nocobase/config/locations/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "GET", "path": "/api/nocobase/config/session-types/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "POST", "path": "/api/nocobase/config/session-types/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN", "body": ["code", "label", "default_capacity?", "is_active?"]},
        {"method": "GET", "path": "/api/nocobase/config/session-types/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "POST/PATCH/PUT", "path": "/api/nocobase/config/session-types/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "DELETE", "path": "/api/nocobase/config/session-types/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "GET", "path": "/api/nocobase/config/payroll/schemes/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "POST", "path": "/api/nocobase/config/payroll/schemes/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN", "body": ["name", "location?", "is_active?"]},
        {"method": "GET", "path": "/api/nocobase/config/payroll/schemes/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "POST/PATCH/PUT", "path": "/api/nocobase/config/payroll/schemes/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "DELETE", "path": "/api/nocobase/config/payroll/schemes/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "GET", "path": "/api/nocobase/config/payroll/rules/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN", "query": ["scheme_id"]},
        {"method": "POST", "path": "/api/nocobase/config/payroll/rules/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN", "body": ["scheme_id", "session_type", "rule_type", "base_amount_minor", "currency?", "min_clients_threshold?", "extra_client_amount_minor?"]},
        {"method": "GET", "path": "/api/nocobase/config/payroll/rules/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "POST/PATCH/PUT", "path": "/api/nocobase/config/payroll/rules/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "DELETE", "path": "/api/nocobase/config/payroll/rules/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "GET", "path": "/api/nocobase/config/payroll/assignments/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN", "query": ["trainer_id"]},
        {"method": "POST", "path": "/api/nocobase/config/payroll/assignments/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN", "body": ["trainer_id", "scheme_id", "effective_from", "effective_to?"]},
        {"method": "GET", "path": "/api/nocobase/config/languages/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "POST", "path": "/api/nocobase/config/languages/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN", "body": ["code", "name", "is_active?"]},
        {"method": "GET", "path": "/api/nocobase/config/languages/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "POST/PATCH/PUT", "path": "/api/nocobase/config/languages/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "DELETE", "path": "/api/nocobase/config/languages/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "GET", "path": "/api/nocobase/config/dictionary-keys/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "POST", "path": "/api/nocobase/config/dictionary-keys/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN", "body": ["domain", "code", "is_active?"]},
        {"method": "GET", "path": "/api/nocobase/config/dictionary-keys/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "POST/PATCH/PUT", "path": "/api/nocobase/config/dictionary-keys/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "DELETE", "path": "/api/nocobase/config/dictionary-keys/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "GET", "path": "/api/nocobase/config/dictionary-translations/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "POST", "path": "/api/nocobase/config/dictionary-translations/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN", "body": ["key_id", "language_code", "value"]},
        {"method": "GET", "path": "/api/nocobase/config/dictionary-translations/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "POST/PATCH/PUT", "path": "/api/nocobase/config/dictionary-translations/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "DELETE", "path": "/api/nocobase/config/dictionary-translations/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "GET", "path": "/api/nocobase/config/notification-template-translations/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN", "query": ["template_id", "language_code"]},
        {"method": "POST", "path": "/api/nocobase/config/notification-template-translations/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN", "body": ["template_id", "language_code", "subject?", "body"]},
        {"method": "GET", "path": "/api/nocobase/config/notification-template-translations/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "POST/PATCH/PUT", "path": "/api/nocobase/config/notification-template-translations/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "DELETE", "path": "/api/nocobase/config/notification-template-translations/<id>/", "roles": ["nocobase"], "auth": "NOCOBASE_CONFIG_TOKEN"},
        {"method": "GET", "path": "/api/client/profile/", "roles": ["client"]},
        {"method": "POST", "path": "/api/client/profile/", "roles": ["client"], "body": ["account", "participant?"]},
        {"method": "GET", "path": "/api/client/consents/", "roles": ["client"]},
        {"method": "POST", "path": "/api/client/consents/", "roles": ["client"], "body": ["type", "granted", "policy_version?"]},
        {"method": "GET", "path": "/api/client/schedule/", "roles": ["client"]},
        {"method": "GET", "path": "/api/client/attendance/", "roles": ["client"]},
        {"method": "GET", "path": "/api/client/payments/", "roles": ["client"]},
        {
            "method": "POST",
            "path": "/api/client/payments/upload-receipt/",
            "roles": ["client"],
            "body": ["student_id?", "amount_minor", "currency?", "paid_at?", "method?", "comment?", "file"],
        },
        {"method": "GET", "path": "/api/trainer/sessions/", "roles": ["trainer"]},
        {"method": "GET", "path": "/api/trainer/groups/", "roles": ["trainer"]},
        {"method": "GET", "path": "/api/trainer/history/", "roles": ["trainer"]},
        {"method": "GET", "path": "/api/trainer/sessions/<id>/", "roles": ["trainer"]},
        {
            "method": "POST",
            "path": "/api/trainer/sessions/<id>/attendance/",
            "roles": ["trainer"],
            "body": ["student_id", "status"],
        },
        {"method": "GET", "path": "/api/admin/api-contract/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/dashboard/", "roles": ["admin"]},
        {
            "method": "GET",
            "path": "/api/admin/reference/",
            "roles": ["admin"],
            "response_keys": [
                "trainers", "groups", "subscription_types", "locations",
                "participants", "choices",
            ],
        },
        {
            "method": "GET",
            "path": "/api/admin/clients/",
            "roles": ["admin"],
            "query": ["q", "active", "group_id", "trainer_id", "debt"],
        },
        {
            "method": "POST",
            "path": "/api/admin/clients/",
            "roles": ["admin"],
            "body": ["client_type", "account", "participant?"],
        },
        {
            "method": "GET",
            "path": "/api/admin/clients/<id>/",
            "roles": ["admin"],
            "response_keys": ["account", "participants", "subscriptions", "charges", "payments", "attendance", "consents", "summary"],
        },
        {"method": "POST/PATCH/PUT", "path": "/api/admin/clients/<id>/", "roles": ["admin"], "body": ["account"]},
        {"method": "DELETE", "path": "/api/admin/clients/<id>/", "roles": ["admin"], "description": "Soft-archive client account and participants."},
        {
            "method": "POST",
            "path": "/api/admin/clients/<id>/participants/",
            "roles": ["admin"],
            "body": ["participant"],
        },
        {"method": "GET", "path": "/api/admin/participants/<id>/", "roles": ["admin"]},
        {"method": "POST/PATCH/PUT", "path": "/api/admin/participants/<id>/", "roles": ["admin"], "body": ["participant"]},
        {"method": "DELETE", "path": "/api/admin/participants/<id>/", "roles": ["admin"], "description": "Soft-archive participant."},
        {"method": "GET", "path": "/api/admin/trainers/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/trainers/", "roles": ["admin"], "body": ["trainer"]},
        {"method": "GET", "path": "/api/admin/trainers/<id>/", "roles": ["admin"]},
        {"method": "POST/PATCH/PUT", "path": "/api/admin/trainers/<id>/", "roles": ["admin"], "body": ["trainer"]},
        {"method": "DELETE", "path": "/api/admin/trainers/<id>/", "roles": ["admin"], "description": "Soft-archive trainer and disable login."},
        {"method": "GET", "path": "/api/admin/groups/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/groups/", "roles": ["admin"], "body": ["group|flat fields"]},
        {"method": "GET", "path": "/api/admin/groups/<id>/", "roles": ["admin"]},
        {"method": "POST/PATCH/PUT", "path": "/api/admin/groups/<id>/", "roles": ["admin"], "body": ["group|flat fields"]},
        {"method": "DELETE", "path": "/api/admin/groups/<id>/", "roles": ["admin"], "description": "Soft-archive group."},
        {"method": "GET", "path": "/api/admin/subscription-types/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/subscription-types/", "roles": ["admin"], "body": ["subscription_type|subscriptionType|flat fields"]},
        {"method": "GET", "path": "/api/admin/subscription-types/<id>/", "roles": ["admin"]},
        {"method": "POST/PATCH/PUT", "path": "/api/admin/subscription-types/<id>/", "roles": ["admin"], "body": ["subscription_type|subscriptionType|flat fields"]},
        {"method": "DELETE", "path": "/api/admin/subscription-types/<id>/", "roles": ["admin"], "description": "Soft-archive subscription type."},
        {"method": "GET", "path": "/api/admin/participants/<id>/subscriptions/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/participants/<id>/subscriptions/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/subscriptions/<id>/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/subscriptions/<id>/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/subscriptions/<id>/renew/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/subscriptions/<id>/freeze/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/subscriptions/<id>/adjust/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/participants/<id>/charges/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/participants/<id>/charges/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/payments/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/payments/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/payments/<id>/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/payments/<id>/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/payments/<id>/confirm/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/payments/<id>/reject/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/schedule/sessions/<id>/attendance/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/schedule/sessions/<id>/attendance/", "roles": ["admin"], "body": ["student_id", "status"]},
        {"method": "GET", "path": "/api/admin/schedule/sessions/<id>/waitlist/", "roles": ["admin"], "query": ["status"]},
        {"method": "POST", "path": "/api/admin/schedule/sessions/<id>/waitlist/", "roles": ["admin"], "body": ["student_id", "priority?", "note?"]},
        {"method": "GET", "path": "/api/admin/schedule/waitlist/<id>/", "roles": ["admin"]},
        {"method": "POST/PATCH/PUT", "path": "/api/admin/schedule/waitlist/<id>/", "roles": ["admin"], "body": ["status?", "priority?", "note?"]},
        {"method": "POST", "path": "/api/admin/schedule/waitlist/<id>/promote/", "roles": ["admin"], "description": "Promote waitlist entry into the concrete session roster."},
        {"method": "DELETE", "path": "/api/admin/schedule/waitlist/<id>/", "roles": ["admin"], "description": "Cancel waitlist entry without deleting history."},
        {"method": "GET", "path": "/api/admin/schedule/templates/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/schedule/templates/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/schedule/templates/<id>/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/schedule/templates/<id>/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/schedule/templates/<id>/generate/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/schedule/templates/<id>/cancel-future/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/schedule/sessions/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/schedule/sessions/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/schedule/sessions/<id>/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/schedule/sessions/<id>/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/schedule/sessions/<id>/cancel/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/schedule/check-conflict/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/debtors/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/upcoming/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/reports/income/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/export/<entity>/<fmt>/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/notifications/templates/", "roles": ["admin"], "query": ["event_type", "channel"]},
        {"method": "POST", "path": "/api/admin/notifications/templates/", "roles": ["admin"], "body": ["event_type", "channel", "subject?", "body"]},
        {"method": "GET", "path": "/api/admin/notifications/templates/<id>/", "roles": ["admin"]},
        {"method": "POST/PATCH/PUT", "path": "/api/admin/notifications/templates/<id>/", "roles": ["admin"], "body": ["template|flat fields"]},
        {"method": "DELETE", "path": "/api/admin/notifications/templates/<id>/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/notifications/rules/", "roles": ["admin"], "query": ["event_type", "channel", "active"]},
        {"method": "POST", "path": "/api/admin/notifications/rules/", "roles": ["admin"], "body": ["event_type", "channel", "template_id", "offset_minutes", "is_active?"]},
        {"method": "GET", "path": "/api/admin/notifications/rules/<id>/", "roles": ["admin"]},
        {"method": "POST/PATCH/PUT", "path": "/api/admin/notifications/rules/<id>/", "roles": ["admin"], "body": ["rule|flat fields"]},
        {"method": "DELETE", "path": "/api/admin/notifications/rules/<id>/", "roles": ["admin"], "description": "Deactivate notification rule."},
        {"method": "GET", "path": "/api/admin/notifications/quiet-hours/", "roles": ["admin"], "query": ["channel", "active"]},
        {"method": "POST", "path": "/api/admin/notifications/quiet-hours/", "roles": ["admin"], "body": ["channel", "starts_at", "ends_at", "timezone", "is_active?"]},
        {"method": "GET", "path": "/api/admin/notifications/quiet-hours/<id>/", "roles": ["admin"]},
        {"method": "POST/PATCH/PUT", "path": "/api/admin/notifications/quiet-hours/<id>/", "roles": ["admin"], "body": ["policy|flat fields"]},
        {"method": "DELETE", "path": "/api/admin/notifications/quiet-hours/<id>/", "roles": ["admin"], "description": "Deactivate quiet-hours policy."},
        {"method": "GET", "path": "/api/admin/notifications/logs/", "roles": ["admin"], "query": ["status", "channel", "event_type", "client_id"]},
        {"method": "GET", "path": "/api/admin/notifications/logs/<id>/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/notifications/logs/<id>/retry/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/notifications/mass-mail/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/payroll/schemes/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/payroll/schemes/", "roles": ["admin"], "body": ["name", "location?", "is_active?"]},
        {"method": "GET", "path": "/api/admin/payroll/schemes/<id>/", "roles": ["admin"]},
        {"method": "POST/PATCH/PUT", "path": "/api/admin/payroll/schemes/<id>/", "roles": ["admin"], "body": ["scheme|flat fields"]},
        {"method": "DELETE", "path": "/api/admin/payroll/schemes/<id>/", "roles": ["admin"], "description": "Deactivate payroll scheme."},
        {"method": "GET", "path": "/api/admin/payroll/rules/", "roles": ["admin"], "query": ["scheme_id"]},
        {"method": "POST", "path": "/api/admin/payroll/rules/", "roles": ["admin"], "body": ["scheme_id", "session_type", "rule_type", "base_amount_minor", "currency?", "min_clients_threshold?", "extra_client_amount_minor?"]},
        {"method": "GET", "path": "/api/admin/payroll/rules/<id>/", "roles": ["admin"]},
        {"method": "POST/PATCH/PUT", "path": "/api/admin/payroll/rules/<id>/", "roles": ["admin"], "body": ["rule|flat fields"]},
        {"method": "DELETE", "path": "/api/admin/payroll/rules/<id>/", "roles": ["admin"], "description": "Deactivate payroll rule."},
        {"method": "GET", "path": "/api/admin/payroll/assignments/", "roles": ["admin"], "query": ["trainer_id"]},
        {"method": "POST", "path": "/api/admin/payroll/assignments/", "roles": ["admin"], "body": ["trainer_id", "scheme_id", "effective_from", "effective_to?"]},
        {"method": "GET", "path": "/api/admin/payroll/periods/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/payroll/periods/", "roles": ["admin"], "body": ["date_from", "date_to", "location?"]},
        {"method": "GET", "path": "/api/admin/payroll/periods/<id>/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/privacy/clients/<id>/export/", "roles": ["admin"], "description": "Download complete client data JSON for RODO/GDPR access requests."},
        {"method": "POST", "path": "/api/admin/privacy/clients/<id>/anonymize/", "roles": ["admin"]},
    ],
}
