API_CONTRACT = {
    "version": "2026-07-06",
    "base_path": "/api/",
    "auth": {
        "type": "django-session",
        "login": {
            "csrf": "GET /api/csrf/ first, then POST /api/auth/login/.",
            "body": ["login|username|email", "password"],
            "logout": "POST /api/auth/logout/",
        },
        "notes": [
            "Admin endpoints require role=admin or superuser.",
            "Trainer endpoints require role=trainer or superuser.",
            "Client endpoints expose role=client while the internal role remains parent.",
        ],
    },
    "conventions": {
        "dates": "YYYY-MM-DD",
        "datetimes": "ISO 8601 with timezone; naive values are interpreted in server timezone.",
        "money": "amount_minor is stored in grosze/cents; formatted amount is returned as amount.",
        "errors": "API errors return JSON: {\"error\": ...}.",
    },
    "resources": {
        "account": ["id", "username", "full_name", "email", "phone", "telegram_chat_id", "created_at"],
        "participant": [
            "id", "first_name", "last_name", "full_name", "email", "is_active",
            "is_account_holder", "group", "client_phone", "emergency_contact_name",
            "emergency_contact_phone",
        ],
        "trainer": ["id", "username", "full_name", "email", "phone", "is_active", "groups_count"],
        "group": ["id", "name", "description", "default_trainer", "is_active", "participants_count"],
        "subscription_type": [
            "id", "name", "price", "price_minor", "currency", "duration_days",
            "sessions_count", "is_unlimited", "is_individual", "is_active",
        ],
        "subscription": [
            "id", "participant_id", "subscription_type_id", "type", "status",
            "start_date", "base_end_date", "effective_end_date", "remaining_sessions",
        ],
        "charge": [
            "id", "participant_id", "participant", "subscription_id", "description",
            "amount", "amount_minor", "currency", "due_date", "created_at",
        ],
        "payment": [
            "id", "participant_id", "participant", "amount", "amount_minor", "currency",
            "paid_at", "method", "status", "comment", "confirmed_by", "confirmed_at",
            "created_at",
        ],
        "session": [
            "id", "template_id", "start_at", "end_at", "location", "session_type",
            "trainer_id", "trainer", "group", "individual_student_id", "is_cancelled",
            "is_manually_modified", "max_participants", "notes",
        ],
    },
    "endpoints": [
        {
            "method": "POST",
            "path": "/api/auth/login/",
            "roles": ["anonymous"],
            "description": "Production session login. Accepts username or email in login/username/email.",
            "body": ["login", "password"],
        },
        {
            "method": "POST",
            "path": "/api/auth/logout/",
            "roles": ["admin", "trainer", "client"],
            "description": "Destroy current Django session.",
        },
        {
            "method": "GET",
            "path": "/api/me/",
            "roles": ["admin", "trainer", "client"],
            "description": "Current authenticated user profile.",
        },
        {
            "method": "GET",
            "path": "/api/client/overview/",
            "roles": ["client"],
            "description": "Client account and participant overview.",
            "response_keys": ["account", "participants", "students"],
        },
        {"method": "GET", "path": "/api/client/profile/", "roles": ["client"]},
        {"method": "POST", "path": "/api/client/profile/", "roles": ["client"], "body": ["account", "participant?"]},
        {"method": "GET", "path": "/api/client/consents/", "roles": ["client"]},
        {"method": "POST", "path": "/api/client/consents/", "roles": ["client"], "body": ["type", "granted", "policy_version?"]},
        {"method": "GET", "path": "/api/client/schedule/", "roles": ["client"]},
        {"method": "GET", "path": "/api/client/attendance/", "roles": ["client"]},
        {"method": "GET", "path": "/api/client/payments/", "roles": ["client"]},
        {
            "method": "POST",
            "path": "/api/client/payments/upload-receipt/",
            "roles": ["client"],
            "body": ["student_id?", "amount_minor", "currency?", "paid_at?", "method?", "comment?", "file"],
        },
        {"method": "GET", "path": "/api/trainer/sessions/", "roles": ["trainer"]},
        {"method": "GET", "path": "/api/trainer/groups/", "roles": ["trainer"]},
        {"method": "GET", "path": "/api/trainer/history/", "roles": ["trainer"]},
        {"method": "GET", "path": "/api/trainer/sessions/<id>/", "roles": ["trainer"]},
        {
            "method": "POST",
            "path": "/api/trainer/sessions/<id>/attendance/",
            "roles": ["trainer"],
            "body": ["student_id", "status"],
        },
        {"method": "GET", "path": "/api/admin/api-contract/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/dashboard/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/reference/", "roles": ["admin"]},
        {
            "method": "GET",
            "path": "/api/admin/clients/",
            "roles": ["admin"],
            "query": ["q", "active", "group_id", "trainer_id", "debt"],
        },
        {
            "method": "POST",
            "path": "/api/admin/clients/",
            "roles": ["admin"],
            "body": ["client_type", "account", "participant?"],
        },
        {
            "method": "GET",
            "path": "/api/admin/clients/<id>/",
            "roles": ["admin"],
            "response_keys": ["account", "participants", "subscriptions", "charges", "payments", "attendance", "consents", "summary"],
        },
        {"method": "POST/PATCH/PUT", "path": "/api/admin/clients/<id>/", "roles": ["admin"], "body": ["account"]},
        {"method": "DELETE", "path": "/api/admin/clients/<id>/", "roles": ["admin"], "description": "Soft-archive client account and participants."},
        {
            "method": "POST",
            "path": "/api/admin/clients/<id>/participants/",
            "roles": ["admin"],
            "body": ["participant"],
        },
        {"method": "GET", "path": "/api/admin/participants/<id>/", "roles": ["admin"]},
        {"method": "POST/PATCH/PUT", "path": "/api/admin/participants/<id>/", "roles": ["admin"], "body": ["participant"]},
        {"method": "DELETE", "path": "/api/admin/participants/<id>/", "roles": ["admin"], "description": "Soft-archive participant."},
        {"method": "GET", "path": "/api/admin/trainers/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/trainers/", "roles": ["admin"], "body": ["trainer"]},
        {"method": "GET", "path": "/api/admin/trainers/<id>/", "roles": ["admin"]},
        {"method": "POST/PATCH/PUT", "path": "/api/admin/trainers/<id>/", "roles": ["admin"], "body": ["trainer"]},
        {"method": "DELETE", "path": "/api/admin/trainers/<id>/", "roles": ["admin"], "description": "Soft-archive trainer and disable login."},
        {"method": "GET", "path": "/api/admin/groups/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/groups/", "roles": ["admin"], "body": ["group|flat fields"]},
        {"method": "GET", "path": "/api/admin/groups/<id>/", "roles": ["admin"]},
        {"method": "POST/PATCH/PUT", "path": "/api/admin/groups/<id>/", "roles": ["admin"], "body": ["group|flat fields"]},
        {"method": "DELETE", "path": "/api/admin/groups/<id>/", "roles": ["admin"], "description": "Soft-archive group."},
        {"method": "GET", "path": "/api/admin/subscription-types/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/subscription-types/", "roles": ["admin"], "body": ["subscription_type|subscriptionType|flat fields"]},
        {"method": "GET", "path": "/api/admin/subscription-types/<id>/", "roles": ["admin"]},
        {"method": "POST/PATCH/PUT", "path": "/api/admin/subscription-types/<id>/", "roles": ["admin"], "body": ["subscription_type|subscriptionType|flat fields"]},
        {"method": "DELETE", "path": "/api/admin/subscription-types/<id>/", "roles": ["admin"], "description": "Soft-archive subscription type."},
        {"method": "GET", "path": "/api/admin/participants/<id>/subscriptions/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/participants/<id>/subscriptions/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/subscriptions/<id>/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/subscriptions/<id>/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/subscriptions/<id>/renew/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/subscriptions/<id>/freeze/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/subscriptions/<id>/adjust/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/participants/<id>/charges/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/participants/<id>/charges/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/payments/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/payments/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/payments/<id>/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/payments/<id>/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/payments/<id>/confirm/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/payments/<id>/reject/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/schedule/sessions/<id>/attendance/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/schedule/sessions/<id>/attendance/", "roles": ["admin"], "body": ["student_id", "status"]},
        {"method": "GET", "path": "/api/admin/schedule/templates/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/schedule/templates/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/schedule/templates/<id>/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/schedule/templates/<id>/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/schedule/templates/<id>/generate/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/schedule/templates/<id>/cancel-future/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/schedule/sessions/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/schedule/sessions/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/schedule/sessions/<id>/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/schedule/sessions/<id>/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/schedule/sessions/<id>/cancel/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/schedule/check-conflict/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/debtors/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/upcoming/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/reports/income/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/export/<entity>/<fmt>/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/notifications/templates/", "roles": ["admin"], "query": ["event_type", "channel"]},
        {"method": "POST", "path": "/api/admin/notifications/templates/", "roles": ["admin"], "body": ["event_type", "channel", "subject?", "body"]},
        {"method": "GET", "path": "/api/admin/notifications/templates/<id>/", "roles": ["admin"]},
        {"method": "POST/PATCH/PUT", "path": "/api/admin/notifications/templates/<id>/", "roles": ["admin"], "body": ["template|flat fields"]},
        {"method": "DELETE", "path": "/api/admin/notifications/templates/<id>/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/notifications/rules/", "roles": ["admin"], "query": ["event_type", "channel", "active"]},
        {"method": "POST", "path": "/api/admin/notifications/rules/", "roles": ["admin"], "body": ["event_type", "channel", "template_id", "offset_minutes", "is_active?"]},
        {"method": "GET", "path": "/api/admin/notifications/rules/<id>/", "roles": ["admin"]},
        {"method": "POST/PATCH/PUT", "path": "/api/admin/notifications/rules/<id>/", "roles": ["admin"], "body": ["rule|flat fields"]},
        {"method": "DELETE", "path": "/api/admin/notifications/rules/<id>/", "roles": ["admin"], "description": "Deactivate notification rule."},
        {"method": "GET", "path": "/api/admin/notifications/logs/", "roles": ["admin"], "query": ["status", "channel", "event_type", "client_id"]},
        {"method": "GET", "path": "/api/admin/notifications/logs/<id>/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/notifications/logs/<id>/retry/", "roles": ["admin"]},
        {"method": "POST", "path": "/api/admin/notifications/mass-mail/", "roles": ["admin"]},
        {"method": "GET", "path": "/api/admin/privacy/clients/<id>/export/", "roles": ["admin"], "description": "Download complete client data JSON for RODO/GDPR access requests."},
        {"method": "POST", "path": "/api/admin/privacy/clients/<id>/anonymize/", "roles": ["admin"]},
    ],
}
