from django.urls import path

from . import views

urlpatterns = [
    path("csrf/", views.csrf, name="api-csrf"),
    path("auth/login/", views.auth_login, name="api-auth-login"),
    path("auth/logout/", views.auth_logout, name="api-auth-logout"),
    path("dev-login/<str:role>/", views.dev_login, name="api-dev-login"),
    path("dev-logout/", views.dev_logout, name="api-dev-logout"),
    path("me/", views.me, name="api-me"),

    path("client/overview/", views.client_overview, name="api-client-overview"),
    path("client/profile/", views.client_profile, name="api-client-profile"),
    path("client/consents/", views.client_consents, name="api-client-consents"),
    path("client/schedule/", views.client_schedule, name="api-client-schedule"),
    path("client/attendance/", views.client_attendance, name="api-client-attendance"),
    path("client/payments/", views.client_payments, name="api-client-payments"),
    path("client/payments/upload-receipt/", views.client_upload_receipt, name="api-client-upload-receipt"),

    path("trainer/sessions/", views.trainer_sessions, name="api-trainer-sessions"),
    path("trainer/groups/", views.trainer_groups, name="api-trainer-groups"),
    path("trainer/history/", views.trainer_history, name="api-trainer-history"),
    path("trainer/sessions/<int:session_id>/", views.trainer_session_detail, name="api-trainer-session-detail"),
    path("trainer/sessions/<int:session_id>/attendance/", views.trainer_mark_attendance, name="api-trainer-attendance"),

    path("admin/clients/", views.admin_clients, name="api-admin-clients"),
    path("admin/clients/<int:client_id>/", views.admin_client_detail, name="api-admin-client-detail"),
    path("admin/clients/<int:client_id>/participants/", views.admin_client_participants,
         name="api-admin-client-participants"),
    path("admin/participants/<int:participant_id>/", views.admin_participant_detail,
         name="api-admin-participant-detail"),
    path("admin/api-contract/", views.admin_api_contract, name="api-admin-api-contract"),
    path("admin/trainers/", views.admin_trainers, name="api-admin-trainers"),
    path("admin/trainers/<int:trainer_id>/", views.admin_trainer_detail,
         name="api-admin-trainer-detail"),
    path("admin/reference/", views.admin_reference, name="api-admin-reference"),
    path("admin/dashboard/", views.admin_dashboard, name="api-admin-dashboard"),
    path("admin/groups/", views.admin_groups, name="api-admin-groups"),
    path("admin/groups/<int:group_id>/", views.admin_group_detail, name="api-admin-group-detail"),
    path("admin/subscription-types/", views.admin_subscription_types,
         name="api-admin-subscription-types"),
    path("admin/subscription-types/<int:subscription_type_id>/", views.admin_subscription_type_detail,
         name="api-admin-subscription-type-detail"),
    path("admin/participants/<int:participant_id>/subscriptions/", views.admin_participant_subscriptions,
         name="api-admin-participant-subscriptions"),
    path("admin/subscriptions/<int:subscription_id>/", views.admin_subscription_detail,
         name="api-admin-subscription-detail"),
    path("admin/subscriptions/<int:subscription_id>/renew/", views.admin_subscription_renew,
         name="api-admin-subscription-renew"),
    path("admin/subscriptions/<int:subscription_id>/freeze/", views.admin_subscription_freeze,
         name="api-admin-subscription-freeze"),
    path("admin/subscriptions/<int:subscription_id>/adjust/", views.admin_subscription_adjust,
         name="api-admin-subscription-adjust"),
    path("admin/participants/<int:participant_id>/charges/", views.admin_participant_charges,
         name="api-admin-participant-charges"),
    path("admin/payments/", views.admin_payments, name="api-admin-payments"),
    path("admin/payments/<int:payment_id>/", views.admin_payment_detail,
         name="api-admin-payment-detail"),
    path("admin/payments/<int:payment_id>/confirm/", views.admin_payment_confirm,
         name="api-admin-payment-confirm"),
    path("admin/payments/<int:payment_id>/reject/", views.admin_payment_reject,
         name="api-admin-payment-reject"),
    path("admin/schedule/templates/", views.admin_schedule_templates,
         name="api-admin-schedule-templates"),
    path("admin/schedule/templates/<int:template_id>/", views.admin_schedule_template_detail,
         name="api-admin-schedule-template-detail"),
    path("admin/schedule/templates/<int:template_id>/generate/", views.admin_schedule_template_generate,
         name="api-admin-schedule-template-generate"),
    path("admin/schedule/templates/<int:template_id>/cancel-future/", views.admin_schedule_template_cancel_future,
         name="api-admin-schedule-template-cancel-future"),
    path("admin/schedule/sessions/", views.admin_schedule_sessions,
         name="api-admin-schedule-sessions"),
    path("admin/schedule/sessions/<int:session_id>/", views.admin_schedule_session_detail,
         name="api-admin-schedule-session-detail"),
    path("admin/schedule/sessions/<int:session_id>/attendance/", views.admin_schedule_session_attendance,
         name="api-admin-schedule-session-attendance"),
    path("admin/schedule/sessions/<int:session_id>/cancel/", views.admin_schedule_session_cancel,
         name="api-admin-schedule-session-cancel"),
    path("admin/schedule/check-conflict/", views.admin_schedule_check_conflict,
         name="api-admin-schedule-check-conflict"),
    path("admin/debtors/", views.admin_debtors, name="api-admin-debtors"),
    path("admin/upcoming/", views.admin_upcoming, name="api-admin-upcoming"),
    path("admin/reports/income/", views.admin_income_report, name="api-admin-income-report"),
    path("admin/export/<str:entity>/<str:fmt>/", views.admin_export, name="api-admin-export"),
    path("admin/notifications/templates/", views.admin_notification_templates,
         name="api-admin-notification-templates"),
    path("admin/notifications/templates/<int:template_id>/", views.admin_notification_template_detail,
         name="api-admin-notification-template-detail"),
    path("admin/notifications/rules/", views.admin_notification_rules,
         name="api-admin-notification-rules"),
    path("admin/notifications/rules/<int:rule_id>/", views.admin_notification_rule_detail,
         name="api-admin-notification-rule-detail"),
    path("admin/notifications/logs/", views.admin_notification_logs,
         name="api-admin-notification-logs"),
    path("admin/notifications/logs/<int:log_id>/", views.admin_notification_log_detail,
         name="api-admin-notification-log-detail"),
    path("admin/notifications/logs/<int:log_id>/retry/", views.admin_notification_retry,
         name="api-admin-notification-retry"),
    path("admin/notifications/mass-mail/", views.admin_mass_mail, name="api-admin-mass-mail"),
    path("admin/privacy/clients/<int:client_id>/anonymize/", views.admin_anonymize_client,
         name="api-admin-anonymize-client"),
    path("admin/privacy/clients/<int:client_id>/export/", views.admin_export_client_data,
         name="api-admin-export-client-data"),
]
