# Generated by Django 5.2.16 on 2026-07-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='currency',
            field=models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EUR'), ('USD', 'USD')], default='PLN', max_length=3),
        ),
        migrations.AddField(
            model_name='group',
            name='price_minor',
            field=models.BigIntegerField(blank=True, help_text='Цена одного занятия в минорных единицах; пусто = не начислять', null=True),
        ),
    ]
