# Generated by Django 5.1.15 on 2026-07-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionledgerentry',
            name='reason',
            field=models.CharField(choices=[('purchase', 'Покупка абонемента (+N)'), ('attendance', 'Посещение (-1)'), ('correction', 'Коррекция статуса посещаемости'), ('manual', 'Ручная корректировка админом'), ('carryover', 'Перенос остатка при продлении')], max_length=16),
        ),
    ]
