# Generated by Django 5.1.15 on 2026-07-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentaccount',
            name='phone',
            field=models.CharField(help_text='Один телефон на семью (без дубликатов)', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='parentaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('phone', ''), _negated=True), fields=('phone',), name='uniq_parent_phone_nonblank'),
        ),
    ]
