# Generated by Django 5.1.15 on 2026-07-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adminotpdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentaccount',
            name='preferred_language',
            field=models.CharField(default='ru', max_length=12),
        ),
    ]
