# Generated by Django 5.1.15 on 2026-07-15 01:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_adminotpdevice'),
        ('scheduling', '0004_alter_session_session_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('location', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('calculated', 'Calculated'), ('approved', 'Approved'), ('exported', 'Exported')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('date_from', 'date_to', 'location'), name='uniq_payroll_period_dates_location')],
            },
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EUR'), ('USD', 'USD')], default='PLN', max_length=3)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_adjustments', to='accounts.trainer')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='payroll.payrollperiod')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('group', 'Групповая'), ('individual', 'Индивидуальная'), ('split', 'Split')], max_length=16)),
                ('rule_type', models.CharField(choices=[('group', 'Group'), ('individual', 'Individual'), ('split', 'Split')], max_length=16)),
                ('base_amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EUR'), ('USD', 'USD')], default='PLN', max_length=3)),
                ('min_clients_threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_client_amount_minor', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='payroll.payrollscheme')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerPayrollAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainer_assignments', to='payroll.payrollscheme')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_assignments', to='accounts.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended_clients_count', models.PositiveIntegerField(default=0)),
                ('base_amount_minor', models.BigIntegerField()),
                ('extra_clients_count', models.PositiveIntegerField(default=0)),
                ('extra_amount_minor', models.BigIntegerField(default=0)),
                ('final_amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EUR'), ('USD', 'USD')], default='PLN', max_length=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_calculations', to='scheduling.session')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_calculations', to='accounts.trainer')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='payroll.payrollperiod')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculations', to='payroll.payrollrule')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('period', 'trainer', 'session'), name='uniq_payroll_calc_period_trainer_session')],
            },
        ),
        migrations.AddConstraint(
            model_name='payrollrule',
            constraint=models.UniqueConstraint(fields=('scheme', 'session_type', 'rule_type'), name='uniq_payroll_rule_scheme_session_rule_type'),
        ),
        migrations.AddIndex(
            model_name='trainerpayrollassignment',
            index=models.Index(fields=['trainer', 'effective_from', 'effective_to'], name='payroll_tra_trainer_0b3259_idx'),
        ),
    ]
